export const ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  ACCESS_DENIED: "ACCESS_DENIED",
  BRANCH_ACCESS_DENIED: "BRANCH_ACCESS_DENIED",
  ORGANIZATION_ACCESS_DENIED: "ORGANIZATION_ACCESS_DENIED",
  USER_SUSPENDED: "USER_SUSPENDED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_REUSED: "TOKEN_REUSED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  DUPLICATE_IDEMPOTENCY_KEY: "DUPLICATE_IDEMPOTENCY_KEY",
  CONCURRENT_UPDATE_CONFLICT: "CONCURRENT_UPDATE_CONFLICT",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  SHIFT_NOT_OPEN: "SHIFT_NOT_OPEN",
  BAD_REQUEST: "BAD_REQUEST"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
